package entity;

public enum Permit {
	// Especialidades,
	CREATE_SPECIALTY,
	UPDATE_SPECIALTY,
	DELETE_SPECIALTY,
	// Paciente
	CREATE_PATIENT,
	READ_PATIENT_PERSONAL_DATA,
	READ_PATIENT_APPOINTMENTS,
	UPDATE_PATIENT,
	DELETE_PATIENT,
	// Doctor
	CREATE_DOCTOR,
	READ_DOCTOR,
	READ_DOCTOR_APPOINTMENTS,
	UPDATE_DOCTOR_PERSONAL_DATA,
	UPDATE_DOCTOR_SCHEDULES,
	DELETE_DOCTOR,
	// Appointment
	CREATE_APPOINTMENT,
	READ_APPOINTMENT,
	UPDATE_APPOINTMENT,
	DELETE_APPOINTMENT,
	// User
	GRANT_PERMISSIONS,
	DENY_PERMISSIONS,
	ASSIGN_DOCTOR,
	RESET_PASSWORD,
	READ_USER_DATA,
	READ_USER_SESSIONS
	
}
